#!/bin/bash

# Define the clusterutils command interface, which just basically looks for
# subcommands in the subcommands directory
clusterutils(){

	local comm=bash
	if [ "$1" == "--source" ];then
		comm=source
		shift
	fi
	local subdir=subcommands
	if [ "$1" == "--completion" ];then
                subdir=completions
                shift
        fi


	local what=$1
        shift

	local file="${CLUSTER_UTILS_ROOT}/cli/${subdir}/${what}"

	if [[ -f "$file" ]]; then
		$comm "$file" "$@"
	else
		echo "Subcommand ${what} doesn't exist. Here's a list of valid subcommands:"
		echo ""
		ls $(clusterutils path cli/subcommands)
	fi
}
export -f clusterutils

# Provide an autocompletion function for clusterutils
_complete_clusterutils(){

	local current="${COMP_WORDS[COMP_CWORD]}"
	local previous="${COMP_WORDS[COMP_CWORD-1]}"

	case "${COMP_CWORD}" in
		1)
			# Get the list of (public) subcommands
        		COMPREPLY=($(cd $(clusterutils path cli/subcommands); ls "$current"* 2>/dev/null))
		;;
		*)
			# Return default completion options (list directory)
			COMPREPLY=($(clusterutils --completion "${COMP_WORDS[1]}"))
	esac
}
complete -F _complete_clusterutils clusterutils
