#!/bin/bash

# Parse the clusters.yaml file using yay (see helpers dir)
yay $(clusterutils path clusters.yaml)

# Convert the returned string into an array
read -r -a children <<< "${clusters[children]}"

# And then remove the clusters_ prefix
echo "${children[@]#clusters_}"
