#!/bin/bash

# Check if the computer already has an ssh key stored
if [ -s ~/.ssh/id_rsa.pub ]; then 
	echo " You already have an ssh key for this computer, no need to create it."
else
	echo " No ssh key was found for this computer, so we are going to generate one"
	echo " Please DO NOT SET A PASSWORD for the key (leave it empty, just press enter)"
	echo ""
	ssh-keygen
fi

echo ""
echo " It's time to send the key to the host, you will be prompt (for the last time) for your password in the host."
echo ""

ssh-copy-id "$1"
